spring:
  datasource:
    url: jdbc:mysql://i7d207.p.ssafy.io:3306/ssafy?serverTimezone=Asia/Seoul
    username: ssafy
    password: Ssafyd207
    driver-class-name: com.mysql.cj.jdbc.Driver


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true



server:
  port: 8081
  servlet:
    contextPath: /


logging:
  file:
    path: logs
  level:
    com.ssafy.CommonPJT.main: warn
    root: info